// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>('https://zfnewzekaxofgrindsmb.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmbmV3emVrYXhvZmdyaW5kc21iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4OTY5MjgsImV4cCI6MjA2NjQ3MjkyOH0.13LwvfbBx4BtFnrkMtQn1sbEx0b93vSwGN5NtbT91Io');