// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>('https://zfnewzekaxofgrindsmb.supabase.co', 'sb_publishable_0QeplWnvs708-xHEdgeV-w_x51TROX9');